# Generated by Django 3.0a1 on 2019-09-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default=None, max_length=100)),
                ('artist', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(default=None, max_length=100)),
                ('rating', models.FloatField(default=None)),
                ('author', models.CharField(default=None, max_length=100)),
                ('author_id', models.IntegerField(default=None)),
                ('key', models.CharField(default=None, max_length=100)),
                ('tuning_name', models.CharField(default=None, max_length=100)),
                ('tuning_value', models.CharField(default=None, max_length=100)),
                ('difficulty', models.CharField(default=None, max_length=100)),
                ('last_edit_by', models.CharField(default=None, max_length=100)),
                ('last_edit_by_id', models.IntegerField(default=None)),
                ('content', models.CharField(default=None, max_length=10000000)),
                ('strumming', models.CharField(default=None, max_length=10000000)),
                ('contributors', models.CharField(default=None, max_length=10000000)),
                ('recommended_tabs', models.CharField(default=None, max_length=10000000)),
            ],
        ),
    ]
