const TOGGLE_SEARCH_COMPONENT = 'components/TOGGLE_SEARCH_COMPONENT';
const TOGGLE_RESULT_COMPONENT = 'components/TOGGLE_RESULT_COMPONENT';

export { TOGGLE_SEARCH_COMPONENT, TOGGLE_RESULT_COMPONENT };
