const TOGGLE_SEARCH_COMPONENT = 'components/TOGGLE_SEARCH_COMPONENT';
const TOGGLE_SIDEBAR_COMPONENT = 'components/TOGGLE_SIDEBAR_COMPONENT';

export { TOGGLE_SEARCH_COMPONENT, TOGGLE_SIDEBAR_COMPONENT };
